// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAIBvKdbOZGJ2z6HZM5XJoFC8sloHXus0',
    appId: '1:250553252113:web:0c358429b7095721b074b0',
    messagingSenderId: '250553252113',
    projectId: 'smart-gift-finder-3f665',
    authDomain: 'smart-gift-finder-3f665.firebaseapp.com',
    storageBucket: 'smart-gift-finder-3f665.firebasestorage.app',
    measurementId: 'G-NZL2P2N90Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdcIt1W6L7IGD_c_HI1hu0FGNi72_7JW8',
    appId: '1:250553252113:android:2a959b66500dc809b074b0',
    messagingSenderId: '250553252113',
    projectId: 'smart-gift-finder-3f665',
    storageBucket: 'smart-gift-finder-3f665.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3mBIuf7OXPcv_6UIG6dE3JrTbx-DCX4E',
    appId: '1:250553252113:ios:9ab28e6fad6787abb074b0',
    messagingSenderId: '250553252113',
    projectId: 'smart-gift-finder-3f665',
    storageBucket: 'smart-gift-finder-3f665.firebasestorage.app',
    iosBundleId: 'com.example.smartGiftFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAIBvKdbOZGJ2z6HZM5XJoFC8sloHXus0',
    appId: '1:250553252113:web:4103fc967e3a4a4db074b0',
    messagingSenderId: '250553252113',
    projectId: 'smart-gift-finder-3f665',
    authDomain: 'smart-gift-finder-3f665.firebaseapp.com',
    storageBucket: 'smart-gift-finder-3f665.firebasestorage.app',
    measurementId: 'G-KKH5EVFM39',
  );
}
